version: 2
updates:
  # GitHub Actions/Workflows
  - package-ecosystem: 'github-actions'
    directory: '/.github'
    schedule:
      interval: 'daily'

  # Published Packages
  - package-ecosystem: 'npm'
    directories: 
      - '/packages/lattice-client-core'
      - '/packages/lattice-client-react'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'America/New_York'
    groups:
      dev-dependencies:
        dependency-type: development
        update-types:
          - minor
          - patch
      prod-dependencies:
        dependency-type: production
        update-types:
          - minor
          - patch

  # Internal Packages
  - package-ecosystem: 'npm'
    directories: 
      - '/packages/eslint-config'
      - '/packages/prettier-config'
      - '/packages/tsconfig'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'America/New_York'
    groups:
      dev-dependencies:
        dependency-type: development
        update-types:
          - minor
          - patch
      prod-dependencies:
        dependency-type: production
        update-types:
          - minor
          - patch

  # Apps
  # - washboard-ui
  - package-ecosystem: 'npm'
    directory: '/apps/washboard-ui'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'America/New_York'
    groups:
      dev-dependencies:
        dependency-type: development
        update-types:
          - minor
          - patch
      prod-dependencies:
        dependency-type: production
        update-types:
          - minor
          - patch
