name: 🐛 Bug Report
description: Report a bug or unexpected behavior in wasmCloud TypeScript
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us understand and reproduce the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Provide detailed steps to reproduce the bug.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
      value: |
        1. 
        2. 
        3. 
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what should have happened...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which part of the repository is affected?
      options:
        - "@wasmcloud/lattice-client-core"
        - "@wasmcloud/lattice-client-react"
        - "Washboard UI"
        - "TypeScript Examples"
        - "Documentation"
        - "Build/Development Tools"
        - "Other"
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Provide information about your environment:
      value: |
        - OS: [e.g., macOS 12.0, Ubuntu 20.04, Windows 11]
        - Node.js version: [e.g., 18.17.0]
        - Yarn version: [e.g., 4.0.0]
        - wasmCloud version: [e.g., 1.0.0]
        - wash CLI version: [e.g., 0.20.0]
        - Browser (if applicable): [e.g., Chrome 115, Firefox 115]
      render: markdown
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs/Output
      description: |
        Paste any relevant error messages, logs, or console output.
        This will be automatically formatted as code.
      render: shell

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: |
        If relevant, include configuration files or settings that might be related to the issue.
        Please remove any sensitive information.
      render: yaml

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: |
        Add any other context about the problem here. Screenshots, network traces, 
        links to related issues, or anything else that might be helpful.

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true