name: ✨ Feature Request
description: Suggest a new feature or enhancement for wasmCloud TypeScript
title: '[Feature]: '
labels: ['enhancement', 'triage']
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in improving wasmCloud TypeScript! Please provide details about the feature you'd like to see.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: |
        What problem would this feature solve? Is your feature request related to a problem?
      placeholder: |
        I'm always frustrated when...
        It would be helpful if...
        Currently there's no way to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: |
        I would like to see...
        The feature should work by...
        This could be implemented as...
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Target Component
      description: Which part of the repository would this feature affect?
      options:
        - '@wasmcloud/lattice-client-core'
        - '@wasmcloud/lattice-client-react'
        - 'Washboard UI'
        - 'TypeScript Examples'
        - 'Documentation'
        - 'Build/Development Tools'
        - 'New Package/Component'
        - 'Other'
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - 'New API/Function'
        - 'UI/UX Enhancement'
        - 'Developer Experience'
        - 'Performance Improvement'
        - 'Integration/Plugin'
        - 'Documentation'
        - 'Tooling/Build'
        - 'Other'
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: |
        Describe any alternative solutions or features you've considered.
        Are there workarounds available?
      placeholder: |
        I've considered...
        As a workaround, I currently...
        Other tools handle this by...

  - type: textarea
    id: examples
    attributes:
      label: Usage Examples
      description: |
        Provide examples of how this feature would be used.
        Include code snippets, API designs, or UI mockups if relevant.
      render: typescript

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - 'Low - Nice to have'
        - 'Medium - Would improve my workflow'
        - 'High - Blocking my use case'
        - 'Critical - Cannot proceed without this'
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impact and Benefits
      description: |
        Who would benefit from this feature? What impact would it have?
      placeholder: |
        This would help...
        The benefit would be...
        It would improve...

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation Willingness
      description: Are you willing to help implement this feature?
      options:
        - label: "I'm willing to submit a PR to implement this feature"
        - label: 'I can help with testing and feedback'
        - label: 'I can help with documentation'
        - label: 'I can provide use case validation'

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: |
        Add any other context, screenshots, links to similar features in other projects,
        or anything else that would be helpful.

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
