package wasmcloud:hello;

interface csv-utils {
  variant input-data {
    csv(string),
    json(string),
  }

  calculate-score: func(data: input-data) -> u32;
}

world hello {
  export csv-utils;
}
