package wasmcloud:http-password-checker;

/// This world represents the functionality that makes the http-password-checker component work
///
world component {
  /// This component acts as a HTTP handler (i.e. it responds to HTTP requests),
  /// and to do that, it must expose a handler function which invokers (e.g. the wasmCloud host, wasmtime, or another component)
  /// can use to send in requests (and receive responses).
  ///
  /// For more information on the wasi:http interface:
  ///   https://github.com/WebAssembly/wasi-http/tree/v0.2.2/wit
  ///
  export wasi:http/incoming-handler@0.2.2;
}
