name = "typescript-bundled-rsbuild"
language = "typescript"
type = "component"
version = "0.1.0"

[component]
wit_world = "hello"
wasm_target = "wasm32-wasip2"

build_command = "npm run install-and-build"
build_artifact = "dist/bundled-rsbuild.wasm"
destination = "build/bundled_rsbuild_s.wasm"
