name = "typescript-http-bundling"
language = "typescript"
type = "component"
version = "0.1.0"

[component]
wit_world = "hello"
wasm_target = "wasm32-wasip2"

build_command = "npm run install-and-build"
build_artifact = "dist/http-bundling.wasm"
destination = "build/http_bundling_s.wasm"