name: Typescript / Setup

description: |
  Setup a Typescript project for building and testing.

branding:
  icon: settings
  color: blue

inputs:
  working-directory:
    description: Working directory
    required: false
    default: ./
  npm-token:
    description: NPM token
    required: false
    default: ''

runs:
  using: composite

  steps:
    - name: Setup Package Manager
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        corepack enable
        yarn --version

    - name: Setup Node.js
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        cache: yarn
        cache-dependency-path: ${{ inputs.working-directory }}/yarn.lock
        node-version-file: ${{ inputs.working-directory }}/.tool-versions

    - name: Skip .npmrc File Configuration
      if: ${{ inputs.npm-token == '' }}
      shell: bash
      run: echo "Skipping NPM token setup"

    - name: Configure .npmrc File
      if: ${{ inputs.npm-token != '' }}
      shell: bash
      run: |
        echo "::group::Creating .npmrc file to home directory"
        echo "//registry.npmjs.org/:_authToken=${{ inputs.npm-token }}" > $HOME/.npmrc
        echo "registry=https://registry.npmjs.org/" >> $HOME/.npmrc
        echo "always-auth=true" >> $HOME/.npmrc
        echo "======================"
        echo ".npmrc file contents:"
        cat $HOME/.npmrc
        echo "======================"
        echo "::endgroup::"

    - name: Configure Turbo Cache
      uses: rharkor/caching-for-turbo@2b4b5b14a8d16b8556a58993a8ac331d56d8906d # v2.3.2

    - name: Install Dependencies
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: yarn install
