name: Typescript / Setup

description: |
  Setup a Typescript project for building and testing.

branding:
  icon: settings
  color: blue

inputs:
  working-directory:
    description: Working directory
    required: false
    default: ./
  npm-token:
    description: NPM token
    required: false
    default: ''
  cache-key:
    description: Cache key
    required: false
    default: 'main'

runs:
  using: composite

  steps:
    - name: Setup Package Manager
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        corepack enable
        yarn --version

    - name: Setup Node.js
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        cache: yarn
        cache-dependency-path: ${{ inputs.working-directory }}/yarn.lock
        node-version-file: ${{ inputs.working-directory }}/.tool-versions

    - name: Skip .npmrc File Configuration
      if: ${{ inputs.npm-token == '' }}
      shell: bash
      run: echo "Skipping NPM token setup"

    - name: Configure .npmrc File
      if: ${{ inputs.npm-token != '' }}
      shell: bash
      run: |
        echo "::group::Creating .npmrc file to home directory"
        echo "//registry.npmjs.org/:_authToken=${{ inputs.npm-token }}" > $HOME/.npmrc
        echo "registry=https://registry.npmjs.org/" >> $HOME/.npmrc
        echo "always-auth=true" >> $HOME/.npmrc
        echo "======================"
        echo ".npmrc file contents:"
        cat $HOME/.npmrc
        echo "======================"
        echo "::endgroup::"

    - name: Cache Turbo Build
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: ${{ inputs.working-directory }}/.turbo
        key: ${{ runner.os }}-turbo-${{ github.sha }}-${{ github.workflow }}-${{ inputs.cache-key || github.job || 'main' }}
        restore-keys: |
          ${{ runner.os }}-turbo-${{ github.sha }}-${{ github.workflow }}-${{ inputs.cache-key || github.job || 'main' }}
          ${{ runner.os }}-turbo-${{ github.sha }}-${{ github.workflow }}-
          ${{ runner.os }}-turbo-${{ github.sha }}-
          ${{ runner.os }}-turbo-

    - name: Install Dependencies
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: yarn install

    - name: Turbo Run Summary
      uses: gacts/run-and-post-run@d803f6920adc9a47eeac4cb6c93dbc2e2890c684 # v1.4.2
      with:
        post: |
          echo "::group::Turbo Run Summary"
          cat ${{ inputs.working-directory }}/.turbo/runs/*.json || echo 'No Turbo Run Summary found'
          echo "::endgroup::"
