name: CI - Release

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true
        description: NPM token for publishing packages
      BOT_APP_ID:
        required: true
        description: GitHub App ID for creating tokens
      BOT_APP_PRIVATE_KEY:
        required: true
        description: GitHub App private key for creating tokens

permissions:
  contents: read

jobs:
  changesets:
    # Only run on main repo, don't try to release on forks
    # Also only run on pushes to main branch, i.e. PRs and merge groups should not run this step
    if: |
      (github.repository == 'wasmCloud/typescript') &&
      (github.event_name == 'push' && github.ref == 'refs/heads/main')

    permissions:
      contents: write       # Needed to commit changesets
      pull-requests: write  # Needed to create pull requests
      id-token: write       # Needed for npm provenance

    runs-on: ubuntu-latest

    steps:
      - name: Get App Token
        id: app-token
        uses: actions/create-github-app-token@21cfef2b496dd8ef5b904c159339626a10ad380e # v1.11.6
        with:
          app-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}

      - name: Get GitHub App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: Configure git as App User
        run: |
          git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
          git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com>'
          git config --global format.signOff true

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Setup Node, Yarn, and Turbo
        uses: ./.github/actions/ts-setup
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}

      - name: Build
        run: yarn build

      - name: Version or Publish
        id: changesets
        uses: changesets/action@06245a4e0a36c064a573d4150030f5ec548e4fcc
        with:
          title: 'chore: update versions'
          commit: 'chore: update versions'
          version: yarn ci:version
          publish: yarn ci:publish
          setupGitUser: false
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Parse Published Packages
        if: ${{ steps.changesets.outputs.published == 'true' }}
        id: parse
        run: |
          # Parse Published Packages
          PACKAGE_VERSIONS=$(echo '${{ steps.changesets.outputs.publishedPackages }}' | jq -c 'map({name: .name, value: .version}) | from_entries')
          echo "packageVersions=$PACKAGE_VERSIONS" >> $GITHUB_OUTPUT
          echo "::group::Published Packages"
          echo $PACKAGE_VERSIONS | jq
          echo "::endgroup::"

    outputs:
      # array of objects with name and version
      publishedPackages: ${{ steps.changesets.outputs.publishedPackages }}
      # object with package name as key and version as value
      packageVersions: ${{ steps.parse.outputs.packageVersions }}

  washboard-ui:
    needs: [changesets]
    if: ${{ contains(fromJson(needs.changesets.outputs.publishedPackages).*.name, 'washboard-ui') }}
    permissions:
      contents: write
    uses: ./.github/workflows/release_washboard-ui.yml
    with:
      version: ${{ fromJson(needs.changesets.outputs.packageVersions).washboard-ui }}
      