name: Examples

on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  meta:
    runs-on: ubuntu-latest
    outputs:
      changed-components: ${{ steps.changes.outputs.components }}
      changed-ci: ${{ steps.changes.outputs.ci }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Check for changes
        id: changes
        uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        with:
          filters: |
            ci:
              - '.github/workflows/examples_.yml'
              - '.github/workflows/examples_component.yml'
            components:
              - 'examples/components/**'


  components:
    name: ${{ matrix.example.folder }}
    if: needs.meta.outputs.changed-ci == 'true' || needs.meta.outputs.changed-components == 'true'
    needs: [meta]
    secrets: inherit
    uses: ./.github/workflows/examples_component.yml
    with:
      folder: ${{ matrix.example.folder }}
      wasm-bin: ${{ matrix.example.wasm-bin }}
      test-command: ${{ matrix.example.test-command }}
      skip-wadm: ${{ matrix.example.skip-wadm && true || false }}
      force: ${{ needs.meta.outputs.changed-ci == 'true' }}
    strategy:
      fail-fast: false
      matrix:
        example:
          # Sample matrix entry for examples
          # - folder: http-hello-world        # Folder name of the example within examples/components/*
          #   wasm-bin: http-hello-world.wasm # Wasm binary filename inside dist/
          #   test-command: TEST_RESULT=1     # Some command that will set TEST_RESULT to 0 or 1

          - folder: http-password-checker
            wasm-bin: http-password-checker.wasm
            test-command: |
              RESPONSE=$(curl http://127.0.0.1:8000/api/v1/check -d '{"value": "test"}' | jq -r '.status' || echo '')
              [[ "$RESPONSE" == 'success' ]] && TEST_RESULT=1 || TEST_RESULT=0

          - folder: http-server-with-hono
            wasm-bin: http_server_with_hono.wasm
            test-command: |
              EXPECTED_DATA="This is some JSON data."
              RESPONSE_DATA=$(curl http://127.0.0.1:8000/api/data | jq -r '.message')
              [[ "$RESPONSE_DATA" == "$EXPECTED_DATA" ]] && TEST_RESULT=1 || TEST_RESULT=0

          - folder: http-streaming
            wasm-bin: http-streaming.wasm
            test-command: |
              RESPONSE=$(curl http://127.0.0.1:8000 | base64 -d | wc -c)
              [[ "$RESPONSE" == '1048576' ]] && TEST_RESULT=1 || TEST_RESULT=0

          - folder: bundled-rsbuild
            wasm-bin: bundled-rsbuild.wasm
            skip-wadm: true
            test-command: |
              npm install && npm run transpile
              RESPONSE=$(npm run --silent demo)
              [[ "$RESPONSE" == '15' ]] && TEST_RESULT=1 || TEST_RESULT=0

          - folder: bundled-esbuild
            wasm-bin: bundled-esbuild.wasm
            skip-wadm: true
            test-command: |
              npm install && npm run transpile
              RESPONSE=$(npm run --silent demo)
              [[ "$RESPONSE" == '8' ]] && TEST_RESULT=1 || TEST_RESULT=0

          - folder: http-axios
            wasm-bin: http-axios.wasm
            skip-wadm: true
            test-command: |
              npm install && npm run transpile
              RESPONSE=$(npm run --silent demo | jq -r '.id')
              [[ "$RESPONSE" == '1' ]] && TEST_RESULT=1 || TEST_RESULT=0

  examples-check:
    needs: [components]
    if: ${{ always() }}
    uses: ./.github/workflows/workflow_check.yml
    with:
      pass-condition: ${{ contains(needs.*.result, 'failure') == false }}
